// Algebra 1 strand (ADR-032). The first eight entries are the Sprint 08/13
// keys, MOVED here byte-compatible: key/strand/title/strandLabel/
// prerequisites/difficultyPrior are unchanged from `concepts.ts` before this
// split — only the new `aliases` field is added, to every concept uniformly
// (Task 2's invariant: every concept needs ≥2). A frozen-key test pins the
// first eight exactly.
import type { Concept } from './types'

export const ALGEBRA1_CONCEPTS: readonly Concept[] = [
  {
    key: 'algebra.linear-equations.one-variable',
    strand: 'linear-equations',
    title: 'One-variable linear equations',
    strandLabel: 'Linear equations',
    prerequisites: [],
    difficultyPrior: 0.2,
    aliases: ['linear equations', 'solve for x', 'one-step equations', 'isolate the variable'],
  },
  {
    key: 'algebra.linear-equations.two-variable',
    strand: 'linear-equations',
    title: 'Two-variable linear equations',
    strandLabel: 'Linear equations',
    prerequisites: ['algebra.linear-equations.one-variable'],
    difficultyPrior: 0.35,
    aliases: ['two variable equations', 'slope-intercept', 'linear equation in two variables'],
  },
  {
    key: 'algebra.exponents.product-rule',
    strand: 'exponents',
    title: 'The product rule for exponents',
    strandLabel: 'Exponents',
    prerequisites: [],
    difficultyPrior: 0.25,
    aliases: ['product rule', 'product of powers', 'multiplying powers', 'same base exponents'],
  },
  {
    key: 'algebra.exponents.power-rule',
    strand: 'exponents',
    title: 'The power rule for exponents',
    strandLabel: 'Exponents',
    prerequisites: ['algebra.exponents.product-rule'],
    difficultyPrior: 0.35,
    aliases: ['power rule', 'power of a power'],
  },
  {
    key: 'algebra.polynomials.expanding',
    strand: 'polynomials',
    title: 'Expanding polynomials',
    strandLabel: 'Polynomials',
    prerequisites: ['algebra.exponents.product-rule'],
    difficultyPrior: 0.35,
    aliases: ['expanding', 'foil', 'distribute', 'binomials'],
  },
  {
    key: 'algebra.quadratics.factoring',
    strand: 'quadratics',
    title: 'Factoring quadratics',
    strandLabel: 'Quadratics',
    prerequisites: ['algebra.polynomials.expanding', 'algebra.linear-equations.one-variable'],
    difficultyPrior: 0.5,
    aliases: ['factoring', 'quadratics', 'parabola', 'factor trinomials'],
  },
  {
    key: 'algebra.quadratics.formula',
    strand: 'quadratics',
    title: 'The quadratic formula',
    strandLabel: 'Quadratics',
    prerequisites: ['algebra.quadratics.factoring'],
    difficultyPrior: 0.55,
    aliases: ['quadratic formula', 'discriminant', 'plus or minus'],
  },
  {
    key: 'algebra.inequalities.linear',
    strand: 'inequalities',
    title: 'Linear inequalities',
    strandLabel: 'Inequalities',
    prerequisites: ['algebra.linear-equations.one-variable'],
    difficultyPrior: 0.3,
    aliases: ['inequalities', 'flip the sign', 'less than or equal', 'greater than or equal'],
  },

  // Additions (ADR-032 appendix, algebra1 strand):
  {
    key: 'algebra.systems.elimination-substitution',
    strand: 'systems',
    title: 'Systems of linear equations',
    strandLabel: 'Systems of equations',
    prerequisites: ['algebra.linear-equations.two-variable'],
    difficultyPrior: 0.4,
    aliases: ['system of equations', 'simultaneous equations', 'elimination method', 'substitution method'],
  },
  {
    key: 'algebra.radicals.simplifying',
    strand: 'radicals',
    title: 'Simplifying radical expressions',
    strandLabel: 'Radicals & exponents',
    prerequisites: ['algebra.exponents.power-rule'],
    difficultyPrior: 0.4,
    aliases: ['simplify radicals', 'square roots', 'simplifying square roots', 'radical expressions'],
  },
  {
    key: 'algebra.radicals.rational-exponents',
    strand: 'radicals',
    title: 'Rational exponents',
    strandLabel: 'Radicals & exponents',
    prerequisites: ['algebra.radicals.simplifying', 'algebra.exponents.power-rule'],
    difficultyPrior: 0.45,
    aliases: ['rational exponents', 'fractional exponents', 'nth roots as exponents'],
  },
  {
    key: 'algebra.absolute-value.equations',
    strand: 'absolute-value',
    title: 'Absolute value equations',
    strandLabel: 'Absolute value',
    prerequisites: ['algebra.linear-equations.one-variable'],
    difficultyPrior: 0.3,
    aliases: ['absolute value equations', 'solve absolute value', 'absolute value'],
  },
  {
    key: 'algebra.absolute-value.inequalities',
    strand: 'absolute-value',
    title: 'Absolute value inequalities',
    strandLabel: 'Absolute value',
    prerequisites: ['algebra.absolute-value.equations', 'algebra.inequalities.linear'],
    difficultyPrior: 0.4,
    aliases: ['absolute value inequalities', 'compound inequalities'],
  },
  {
    key: 'algebra.functions.notation',
    strand: 'functions',
    title: 'Function notation & evaluation',
    strandLabel: 'Functions',
    prerequisites: ['algebra.linear-equations.one-variable'],
    difficultyPrior: 0.3,
    aliases: ['function notation', 'f of x', 'evaluating functions'],
  },
  {
    key: 'algebra.functions.graphs',
    strand: 'functions',
    title: 'Graphing & interpreting functions',
    strandLabel: 'Functions',
    prerequisites: ['algebra.functions.notation'],
    difficultyPrior: 0.4,
    aliases: ['graphing functions', 'domain and range', 'function graphs'],
  },
  {
    key: 'algebra.ratios.proportions',
    strand: 'ratios-percent',
    title: 'Ratios & proportions',
    strandLabel: 'Ratios & percent',
    prerequisites: [],
    difficultyPrior: 0.2,
    aliases: ['ratios', 'proportions', 'cross multiply', 'solving proportions'],
  },
  {
    key: 'algebra.ratios.percent',
    strand: 'ratios-percent',
    title: 'Percent problems',
    strandLabel: 'Ratios & percent',
    prerequisites: ['algebra.ratios.proportions'],
    difficultyPrior: 0.3,
    aliases: ['percent change', 'markup and discount', 'percent problems'],
  },
]
