// Algebra 2 strand (ADR-032 appendix): polynomial division & factor theorem,
// rational expressions & equations, exponential functions, logarithms &
// properties, sequences & series, complex numbers, nonlinear systems.
import type { Concept } from './types'

export const ALGEBRA2_CONCEPTS: readonly Concept[] = [
  {
    key: 'algebra2.polynomials.division-factor-theorem',
    strand: 'polynomial-division',
    title: 'Polynomial division & factor theorem',
    strandLabel: 'Polynomial division',
    prerequisites: ['algebra.quadratics.factoring'],
    difficultyPrior: 0.55,
    aliases: ['polynomial division', 'synthetic division', 'factor theorem', 'remainder theorem'],
  },
  {
    key: 'algebra2.rational.simplifying',
    strand: 'rational-expressions',
    title: 'Simplifying rational expressions',
    strandLabel: 'Rational expressions',
    prerequisites: ['algebra2.polynomials.division-factor-theorem'],
    difficultyPrior: 0.5,
    aliases: ['rational expressions', 'simplifying fractions with variables', 'common denominators'],
  },
  {
    key: 'algebra2.rational.equations',
    strand: 'rational-expressions',
    title: 'Solving rational equations',
    strandLabel: 'Rational expressions',
    prerequisites: ['algebra2.rational.simplifying'],
    difficultyPrior: 0.6,
    aliases: ['rational equations', 'cross multiplying equations', 'extraneous solutions'],
  },
  {
    key: 'algebra2.exponential.functions',
    strand: 'exponential-functions',
    title: 'Exponential functions',
    strandLabel: 'Exponential functions',
    prerequisites: ['algebra.radicals.rational-exponents'],
    difficultyPrior: 0.5,
    aliases: ['exponential growth', 'exponential decay', 'exponential functions', 'compound interest'],
  },
  {
    key: 'algebra2.logarithms.intro',
    strand: 'logarithms',
    title: 'Introduction to logarithms',
    strandLabel: 'Logarithms',
    prerequisites: ['algebra2.exponential.functions'],
    difficultyPrior: 0.55,
    aliases: ['logarithms', 'log base', 'converting log to exponential form'],
  },
  {
    key: 'algebra2.logarithms.properties',
    strand: 'logarithms',
    title: 'Logarithm properties & change of base',
    strandLabel: 'Logarithms',
    prerequisites: ['algebra2.logarithms.intro'],
    difficultyPrior: 0.6,
    aliases: ['log rules', 'log properties', 'change of base', 'expanding logarithms'],
  },
  {
    key: 'algebra2.sequences.arithmetic',
    strand: 'sequences-series',
    title: 'Arithmetic sequences & series',
    strandLabel: 'Sequences & series',
    prerequisites: [],
    difficultyPrior: 0.4,
    aliases: ['arithmetic sequence', 'arithmetic series', 'common difference'],
  },
  {
    key: 'algebra2.sequences.geometric',
    strand: 'sequences-series',
    title: 'Geometric sequences & series',
    strandLabel: 'Sequences & series',
    prerequisites: ['algebra2.sequences.arithmetic'],
    difficultyPrior: 0.5,
    aliases: ['geometric sequence', 'geometric series', 'common ratio'],
  },
  {
    key: 'algebra2.complex.numbers',
    strand: 'complex-numbers',
    title: 'Complex numbers',
    strandLabel: 'Complex numbers',
    prerequisites: ['algebra.quadratics.formula'],
    difficultyPrior: 0.55,
    aliases: ['complex numbers', 'imaginary numbers', 'i squared', 'complex conjugate'],
  },
  {
    key: 'algebra2.systems.nonlinear',
    strand: 'nonlinear-systems',
    title: 'Nonlinear systems',
    strandLabel: 'Nonlinear systems',
    prerequisites: ['algebra.systems.elimination-substitution', 'algebra.quadratics.factoring'],
    difficultyPrior: 0.6,
    aliases: ['nonlinear systems', 'system with a parabola', 'quadratic-linear system'],
  },
]
