// Calculus strand (ADR-032 appendix): limits & continuity through intro
// differential equations — AP Calc AB + a first college calculus course.
// `calculus.limits.formal` builds on `precalc.limits.intuitive`
// (trig-precalc.ts) — the precalc/calc bridge named in the sprint plan.
import type { Concept } from './types'

export const CALCULUS_CONCEPTS: readonly Concept[] = [
  {
    key: 'calculus.limits.formal',
    strand: 'limits',
    title: 'Limits & continuity',
    strandLabel: 'Limits',
    prerequisites: ['precalc.limits.intuitive'],
    difficultyPrior: 0.55,
    aliases: ['limits', 'continuity', 'limit laws', 'epsilon delta'],
  },
  {
    key: 'calculus.derivatives.as-limit',
    strand: 'derivatives',
    title: 'The derivative as a limit',
    strandLabel: 'Derivatives',
    prerequisites: ['calculus.limits.formal'],
    difficultyPrior: 0.6,
    aliases: ['derivative definition', 'difference quotient', 'derivative as a limit'],
  },
  {
    key: 'calculus.differentiation.power-rule',
    strand: 'differentiation-rules',
    title: 'Power rule for derivatives',
    strandLabel: 'Differentiation rules',
    prerequisites: ['calculus.derivatives.as-limit'],
    difficultyPrior: 0.55,
    aliases: ['power rule derivative', 'differentiating polynomials'],
  },
  {
    key: 'calculus.differentiation.product-rule',
    strand: 'differentiation-rules',
    title: 'Product rule',
    strandLabel: 'Differentiation rules',
    prerequisites: ['calculus.differentiation.power-rule'],
    difficultyPrior: 0.6,
    aliases: ['product rule derivative', 'differentiating a product'],
  },
  {
    key: 'calculus.differentiation.quotient-rule',
    strand: 'differentiation-rules',
    title: 'Quotient rule',
    strandLabel: 'Differentiation rules',
    prerequisites: ['calculus.differentiation.power-rule'],
    difficultyPrior: 0.6,
    aliases: ['quotient rule derivative', 'differentiating a fraction'],
  },
  {
    key: 'calculus.differentiation.chain-rule',
    strand: 'chain-rule',
    title: 'Chain rule',
    strandLabel: 'Chain rule',
    prerequisites: ['calculus.differentiation.product-rule', 'calculus.differentiation.quotient-rule'],
    difficultyPrior: 0.65,
    aliases: ['chain rule', 'composite function derivative'],
  },
  {
    key: 'calculus.differentiation.implicit',
    strand: 'implicit-differentiation',
    title: 'Implicit differentiation',
    strandLabel: 'Implicit differentiation',
    prerequisites: ['calculus.differentiation.chain-rule'],
    difficultyPrior: 0.7,
    aliases: ['implicit differentiation', 'differentiating both sides'],
  },
  {
    key: 'calculus.applications.related-rates',
    strand: 'applications-of-derivatives',
    title: 'Related rates',
    strandLabel: 'Applications of derivatives',
    prerequisites: ['calculus.differentiation.implicit'],
    difficultyPrior: 0.75,
    aliases: ['related rates', 'rates of change problems'],
  },
  {
    key: 'calculus.applications.optimization',
    strand: 'applications-of-derivatives',
    title: 'Optimization',
    strandLabel: 'Applications of derivatives',
    prerequisites: ['calculus.differentiation.chain-rule'],
    difficultyPrior: 0.75,
    aliases: ['optimization', 'maximize minimize', 'optimization problems'],
  },
  {
    key: 'calculus.applications.curve-sketching',
    strand: 'applications-of-derivatives',
    title: 'Curve sketching',
    strandLabel: 'Applications of derivatives',
    prerequisites: ['calculus.differentiation.chain-rule'],
    difficultyPrior: 0.65,
    aliases: ['curve sketching', 'increasing decreasing', 'concavity', 'first and second derivative test'],
  },
  {
    key: 'calculus.integration.antiderivatives',
    strand: 'antiderivatives',
    title: 'Antiderivatives & indefinite integrals',
    strandLabel: 'Antiderivatives',
    prerequisites: ['calculus.differentiation.power-rule'],
    difficultyPrior: 0.55,
    aliases: ['antiderivatives', 'indefinite integral', 'integration basics'],
  },
  {
    key: 'calculus.integration.definite-ftc',
    strand: 'definite-integrals',
    title: 'Definite integrals & the Fundamental Theorem of Calculus',
    strandLabel: 'Definite integrals',
    prerequisites: ['calculus.integration.antiderivatives'],
    difficultyPrior: 0.65,
    aliases: ['definite integral', 'fundamental theorem of calculus', 'FTC'],
  },
  {
    key: 'calculus.integration.u-substitution',
    strand: 'u-substitution',
    title: 'u-substitution',
    strandLabel: 'u-substitution',
    prerequisites: ['calculus.differentiation.chain-rule', 'calculus.integration.antiderivatives'],
    difficultyPrior: 0.7,
    aliases: ['u-sub', 'u substitution', 'substitution integration'],
  },
  {
    key: 'calculus.integration.area-between-curves',
    strand: 'applications-of-integration',
    title: 'Area between curves',
    strandLabel: 'Applications of integration',
    prerequisites: ['calculus.integration.definite-ftc'],
    difficultyPrior: 0.7,
    aliases: ['area between curves', 'area between two functions'],
  },
  {
    key: 'calculus.integration.volumes',
    strand: 'applications-of-integration',
    title: 'Volumes of revolution',
    strandLabel: 'Applications of integration',
    prerequisites: ['calculus.integration.area-between-curves'],
    difficultyPrior: 0.8,
    aliases: ['volumes of revolution', 'disk method', 'washer method'],
  },
  {
    key: 'calculus.differential-equations.intro',
    strand: 'differential-equations',
    title: 'Introduction to differential equations',
    strandLabel: 'Differential equations',
    prerequisites: ['calculus.integration.antiderivatives'],
    difficultyPrior: 0.75,
    aliases: ['differential equations', 'separable equations', 'slope fields'],
  },
]
