// Geometry strand (ADR-032 appendix): angles & parallel lines, triangle
// congruence, similarity, right-triangle trig, circles, area & volume,
// coordinate geometry & transformations.
import type { Concept } from './types'

export const GEOMETRY_CONCEPTS: readonly Concept[] = [
  {
    key: 'geometry.angles.parallel-lines',
    strand: 'angles',
    title: 'Angles & parallel lines',
    strandLabel: 'Angles',
    prerequisites: [],
    difficultyPrior: 0.3,
    aliases: ['parallel lines', 'transversal', 'alternate interior angles', 'corresponding angles'],
  },
  {
    key: 'geometry.triangles.congruence',
    strand: 'triangle-congruence',
    title: 'Triangle congruence',
    strandLabel: 'Triangle congruence',
    prerequisites: ['geometry.angles.parallel-lines'],
    difficultyPrior: 0.4,
    aliases: ['triangle congruence', 'SSS', 'SAS', 'ASA', 'congruent triangles'],
  },
  {
    key: 'geometry.triangles.similarity',
    strand: 'similarity',
    title: 'Similarity',
    strandLabel: 'Similarity',
    prerequisites: ['geometry.triangles.congruence'],
    difficultyPrior: 0.45,
    aliases: ['similar triangles', 'similarity', 'AA similarity', 'scale factor'],
  },
  {
    key: 'geometry.trig.right-triangle',
    strand: 'right-triangle-trig',
    title: 'Right-triangle trig (SOH-CAH-TOA)',
    strandLabel: 'Right-triangle trig',
    prerequisites: ['geometry.triangles.similarity'],
    difficultyPrior: 0.5,
    aliases: ['SOH CAH TOA', 'right triangle trig', 'sine cosine tangent', 'solving right triangles'],
  },
  {
    key: 'geometry.circles.arcs-angles',
    strand: 'circles',
    title: 'Circle arcs & angles',
    strandLabel: 'Circles',
    prerequisites: ['geometry.angles.parallel-lines'],
    difficultyPrior: 0.45,
    aliases: ['arcs', 'inscribed angles', 'central angles', 'circle theorems'],
  },
  {
    key: 'geometry.circles.area-circumference',
    strand: 'circles',
    title: 'Circle area & circumference',
    strandLabel: 'Circles',
    prerequisites: [],
    difficultyPrior: 0.3,
    aliases: ['circumference', 'area of a circle', 'pi', 'circle area'],
  },
  {
    key: 'geometry.measurement.area',
    strand: 'area-volume',
    title: 'Area of polygons',
    strandLabel: 'Area & volume',
    prerequisites: [],
    difficultyPrior: 0.3,
    aliases: ['area of polygons', 'area formulas', 'area of a triangle', 'area of a trapezoid'],
  },
  {
    key: 'geometry.measurement.volume',
    strand: 'area-volume',
    title: 'Volume & surface area of solids',
    strandLabel: 'Area & volume',
    prerequisites: ['geometry.measurement.area'],
    difficultyPrior: 0.45,
    aliases: ['volume', 'surface area', 'prisms and cylinders', 'volume of a solid'],
  },
  {
    key: 'geometry.coordinate.distance-midpoint',
    strand: 'coordinate-geometry',
    title: 'Coordinate geometry',
    strandLabel: 'Coordinate geometry',
    prerequisites: [],
    difficultyPrior: 0.35,
    aliases: ['distance formula', 'midpoint formula', 'coordinate geometry', 'slope of a line'],
  },
  {
    key: 'geometry.transformations.rigid-and-dilation',
    strand: 'transformations',
    title: 'Transformations',
    strandLabel: 'Transformations',
    prerequisites: ['geometry.coordinate.distance-midpoint'],
    difficultyPrior: 0.4,
    aliases: ['transformations', 'reflections', 'rotations', 'dilations', 'translations'],
  },
]
